# -*- coding: utf-8 -*-
"""SensorAlgorithm

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-dp5roN2WtNWFd2iZkL0h-e_-hKUvY1
"""

import scipy.optimize as op
import math

import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials

gc = gspread.authorize(GoogleCredentials.get_application_default())

worksheet = gc.open('TestBatch1').sheet1

# get_all_values gives a list of rows.
rows = worksheet.get_all_values()
print(rows)

# Convert to a DataFrame and render.
dftrain = pd.DataFrame.from_records(rows)

y = dftrain.pop(0)

m = len(y)
dftrain.insert(0, "Ones", np.ones((m,), dtype=int))

x = dftrain

x = (x.values).astype(np.int)
y = (y.values).astype(np.int)

def Sigmoid(z):
    return 1/(1 + np.exp(-z));

def Gradient(theta,x,y):
    m , n = x.shape
    theta = theta.reshape((n,1));
    y = y.reshape((m,1))
    sigmoid_x_theta = Sigmoid(x.dot(theta));
    grad = ((x.T).dot(sigmoid_x_theta-y))/m;
    return grad.flatten();

def CostFunc(theta,x,y):
    m,n = x.shape; 
    theta = theta.reshape((n,1));
    y = y.reshape((m,1));
    term1 = np.log(Sigmoid(x.dot(theta)));
    term2 = np.log(1-Sigmoid(x.dot(theta)));
    term1 = term1.reshape((m,1))
    term2 = term2.reshape((m,1))
    term = y * term1 + (1 - y) * term2;
    J = -((np.sum(term))/m);
    return J;

# intialize X and y
# X = np.array([[1,2,3],[1,3,4]]);
# y = np.array([[1],[0]]);

m , n = x.shape;
initial_theta = np.zeros(n);
Result = op.minimize(fun = CostFunc, 
                                 x0 = initial_theta, 
                                 args = (x, y),
                                 method = 'TNC',
                                 jac = Gradient);
optimal_theta = Result.x;

def hypothesis(x, theta):
  h = 1/(1+math.exp(-(np.dot(x, theta))))
  return h

value = hypothesis([1, 157952], optimal_theta)
print(value);

if value <= .1:
  print("Person is not in the room")
if value >= .1 and value <= .3:
  print("Person may be in the room")
if value >= .3:
  print("Person is in the room.")