# -*- coding: utf-8 -*-
"""SensorAlgorithmkNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K8Qd0Yo158kDYpqadvDQMwgvFiDiLOWQ

**Setup**

import necessary libraries, manipulate data in order to get time (stored in df 'x') and boolean sound values (stored in df 'y').
"""

import numpy as np
import pandas as pd

import seaborn as sns

from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials

gc = gspread.authorize(GoogleCredentials.get_application_default())

worksheet = gc.open('sound-data5').sheet1

# get_all_values gives a list of rows.
rows = worksheet.get_all_values()
print(rows)

# Convert to a DataFrame and render.
dftrain = pd.DataFrame.from_records(rows)
dftrain = dftrain.drop([0])

y = dftrain.pop(1)

x = dftrain

print(x)

print(y)

x = x.values.astype(float)
y = y.values.astype(float)

"""**Step-One Analysis**

Create test matrices, train dataset with k-Nearest-Neighbors algorithm in order to extract probability of a sound being heard at a given time.
"""

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = .2)

print(len(X_train))
print(len(Y_train))

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 50, weights='uniform', algorithm='auto')
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

classifier.predict(X_test)

print(classifier.predict([[28800000]]))

import matplotlib.pyplot as plt

predictions = []
_x = []
for i in x[:,0]:
  predictions.append((classifier.predict_proba([[i]])).item(0))
  _x.append(i)

sns.scatterplot(x = predictions, y = _x)
plt.xlabel("Predictions [boolean]")
plt.ylabel("Time [millis]")

probabilityDF = pd.DataFrame()
for j in x[:,0]:
  probability = (classifier.predict_proba([[j]])).item(0)
  probabilityDF = probabilityDF.append([[j, probability]])

probabilityDF.head()

"""(delete this later) Ishan, here is the probability dataframe. It is called 'probabilityDF'.

**Step-Two Analysis**

Categorize probabilities (ishan you should fill this part in)
"""

print(probabilityDF)